---


# Adicionando o repositorio do Atom

- name: "Importando a chave do repositorio do Atom"
  rpm_key:
    key: "https://packagecloud.io/AtomEditor/atom/gpgkey"
    state: present
  become: true
  tags:
    - repo
    - atom


- name: "Copiando arquivo de repositório do Atom"
  copy:
    src: "atom-rpm.repo"
    dest: "/etc/yum.repos.d/atom.repo"
    owner: root
    group: root
    mode: '0644'
  become: true
  tags:
    - repo
    - atom


# Instalando o Atom

- name: Instalando o Atom
  dnf:
    name: atom
    state: present
  become: true
  tags:
    - atom
